### ISSUE TITLE
Doesnt work for restoring to CFW

### ISSUE THREAD

**Issue by LetsUnlockiPhone** [MatthewPierson/iPhone-5s-OTA-Downgrade-Patches#2]
The downgrade works fine. So I decided to give a try and restore it to custom 10.3.3 firmware

ERROR: Unable to receive data from ASR
ERROR: Unable to receive validation packet
ERROR: ASR was unable to validate the filesystem
ERROR: Unable to send filesystem
ERROR: Unable to successfully restore device

**Comment by MatthewPierson** [comment]
You need to do a lot more for a CFW, starting with patching ASR

**Comment by LetsUnlockiPhone** [comment]
But its possible to use checkm8 instead of direct nand attack right?

**Comment by MatthewPierson** [comment]
I don't know what you mean by that sorry,
